force-app/main/default/objects/ExternalUser__c/ExternalUser__c.object-meta.xml
<CustomObject>
    <label>ExternalUser</label>
    <nameField>
        <label>User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ExternalUsers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ExternalUser__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>40</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/ExternalUser__c/fields/SecurityToken__c.field-meta.xml
<CustomField>
    <fullName>SecurityToken__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SecurityToken</label>
    <referenceTo>SecurityToken__c</referenceTo>
    <relationshipLabel>ExternalUsers</relationshipLabel>
    <relationshipName>ExternalUsers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SecurityToken__c/SecurityToken__c.object-meta.xml
<CustomObject>
    <label>SecurityToken</label>
    <nameField>
        <label>SecurityTokens Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SecurityTokens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SecurityToken__c/fields/AccessToken__c.field-meta.xml
<CustomField>
    <fullName>AccessToken__c</fullName>
    <label>AccessToken</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/SecurityToken__c/fields/ExternalUser__c.field-meta.xml
<CustomField>
    <fullName>ExternalUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ExternalUser</label>
    <referenceTo>ExternalUser__c</referenceTo>
    <relationshipLabel>SecurityTokens</relationshipLabel>
    <relationshipName>SecurityTokens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SecurityToken__c/fields/RefreshToken__c.field-meta.xml
<CustomField>
    <fullName>RefreshToken__c</fullName>
    <label>RefreshToken</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/classes/RegistrattionController.cls
public class RegistrattionController {
    
    public RegistrattionController(){
        userInfo = new ExternalUser__c();
    }
    
    public ExternalUser__c userInfo {get; set;}
    public String userEmail {get; set;}
    public String userPassword {get; set;}
    
    public PageReference doRegistration(){
        if(!String.isBlank(userEmail)){
            if(UserInfo.Password__c == userPassword){
                List<ExternalUser__c> userList = new List<ExternalUser__c>([SELECT Id,Name 
                                                                            FROM ExternalUser__c 
                                                                            WHERE Email__c =: userEmail 
                                                                            Limit 1]);
                if(userList.isEmpty()){
                    userInfo.Email__c = userEmail;
                    Database.SaveResult insertResult = Database.insert(userInfo);
                    
                    if(insertResult.isSuccess()){
                        List<String> tokens = TokenRandomGenerete.generateRandomToken();
                        SecurityToken__c saveUserTokens = new SecurityToken__c();
                        saveUserTokens.Accesstoken__c = tokens[0];
                        saveUserTokens.Refreshtoken__c = tokens[1];
                        saveUserTokens.Externaluser__c = userInfo.Id;
                        Database.SaveResult insertTokens = Database.insert(saveUserTokens);
                        if(insertTokens.isSuccess()){
                            String data = saveUserTokens.RefreshToken__c;
                            HashTokenForCookie token = new HashTokenForCookie(data);
                            if(String.isNotBlank(token.signature)){
                                Cookie cookie = new Cookie('refreshCookie',token.signature+' '+userInfo.Id,null,600,true);
                                ApexPages.currentPage().setCookies(new Cookie[]{cookie});  
                            }
                            data = saveUserTokens.Accesstoken__c;
                            token = new HashTokenForCookie(data);
                            if(String.isNotBlank(token.signature)){
                                Cookie cookie = new Cookie('accessCookie',token.signature+' '+userInfo.Id,null,1440,true);
                                ApexPages.currentPage().setCookies(new Cookie[]{cookie});  
                                return null;//new PageReference('/apex/ExternalUserForm');
                            }
                        }
                    }
                }else{ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'User with this Email alredy exist'));}
            }else{ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'Passwords doesnt match'));}
        }else{ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'All fields are required'));}
        return null;
    }
    
}